# Generated by Django 2.2.4 on 2024-05-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='itinerary',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='Destination',
            new_name='destination',
        ),
    ]
